"""create users table

Revision ID: 4a2d87c171df
Revises: c3583db888b0
Create Date: 2025-06-09 14:08:12.654184

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a2d87c171df"
down_revision: Union[str, None] = "c3583db888b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name != "sqlite":
        op.alter_column(
            "exchange_rates",
            "rate",
            existing_type=sa.NUMERIC(precision=10, scale=6),
            type_=sa.Numeric(precision=20, scale=6),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name != "sqlite":
        op.alter_column(
            "exchange_rates",
            "rate",
            existing_type=sa.Numeric(precision=20, scale=6),
            type_=sa.NUMERIC(precision=10, scale=6),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
