"""create users table

Revision ID: b69f29217934
Revises: cf3ac488a287
Create Date: 2025-06-08 12:10:45.346290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b69f29217934"
down_revision: Union[str, None] = "cf3ac488a287"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    budgettypeenum = sa.Enum("monthly", "yearly", name="budgettype")
    budgettypeenum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "budgets",
        sa.Column(
            "period", sa.Enum("monthly", "yearly", name="budgettype"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("budgets", "period")
    # ### end Alembic commands ###
    budget_type_enum = sa.Enum("monthly", "yearly", name="budgettype")
    budget_type_enum.drop(op.get_bind(), checkfirst=True)
