"""create users table

Revision ID: c3583db888b0
Revises: cf315accd753
Create Date: 2025-06-09 11:28:06.662139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3583db888b0'
down_revision: Union[str, None] = 'cf315accd753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_rates', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('exchange_rates', 'currency',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=3),
               existing_nullable=False)
    op.create_unique_constraint(None, 'exchange_rates', ['currency'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exchange_rates', type_='unique')
    op.alter_column('exchange_rates', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('exchange_rates', 'id')
    # ### end Alembic commands ###
