name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Set test environment variables
        run: |
          echo "SECRET_KEY=testsecret" >> $GITHUB_ENV
          echo "ALGORITHM=HS256" >> $GITHUB_ENV
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=30" >> $GITHUB_ENV
          echo "REFRESH_TOKEN_EXPIRE_DAYS=5" >> $GITHUB_ENV
          echo "REDIS_URL=redis://localhost:6379/0" >> $GITHUB_ENV
          echo "TEST_DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5433/finance_db_test" >> $GITHUB_ENV
          echo "TEST_SYNC_DATABASE_URL=postgresql+psycopg2://postgres:postgres@localhost:5433/finance_db_test" >> $GITHUB_ENV

      - name: Run tests
        run: |
          poetry run pytest tests
